import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
     <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable}
          
        `}
      >
        {/* Fixed / Sticky Navbar safe */}
        <Navbar />

        {/* Page Wrapper */}
        <main
          className="
            min-h-[calc(100vh-64px)]
            pt-6
            px-3 sm:px-6 lg:px-8 dark:bg-gray-900
          "
        >
          {children}
        </main>
      </body>
    </html>
  );
}

// antialiased min-h-screen
          //  bg-gray-50
          //  bg-white text-black dark:bg-gray-950 dark:text-white transition-colors duration-300

